image:
  registry: registry.gitlab.com
  repository: gitlab-org/gitlab-runner
  # tag: "17.7.0"
  pullPolicy: IfNotPresent

replicas: 2
# gitlabUrl: https://192.168.1.76:9988/
gitlabUrl: https://gitlab.optiplex3060:9988/
gitlabRunner:
  # tlsVerify: false
  image:
    tag: "17.7.0"
runnerToken: "L3cKXUo4U_iuV7pnEev8"

serviceAccount:
  create: false
  name: "ns-gr-service-account"

volumes:
  - name: custom-hosts
    configMap:
      name: custom-etc-hosts-file
volumeMounts:
  - name: custom-etc-hosts-file
    mountPath: /etc/hosts
    subPath: hosts

