apiVersion: v1
kind: Pod
metadata:
  name: gitlab-tls-debug-pod
  namespace: ns-gr
spec:
  hostAliases:
    - ip: "192.168.1.76"
      hostnames:
        - "gitlab.optiplex3060"
  containers:
    - name: curl-container
      image: curlimages/curl:latest
      command:
        - "sh"
        - "-c"
        - |
            curl -v --cacert /etc/ssl/certs/gitlab.crt https://gitlab.optiplex3060:9988/
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
        requests:
          memory: "64Mi"
          cpu: "250m"
      volumeMounts:
        - name: gitlab-tls
          mountPath: /etc/ssl/certs/gitlab.crt
          subPath: gitlab.crt
  volumes:
    - name: gitlab-tls
      secret:
        secretName: gitlab-tls
