apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: ns-gr
spec:
  # serviceAccountName: default  # Utilisation du ServiceAccount 'default' dans gitlab-runner
  containers:
  - name: test-container
    image: curlimages/curl:latest #alpine #busybox
    command: ["sleep", "3600"]
    # securityContext:
    #   runAsUser: 0  # S'assurer que le pod tourne en root
    volumeMounts:
    - name: gitlab-tls-volume
      mountPath: /etc/gitlab-tls
      readOnly: true
    - name: custom-hosts
      mountPath: /etc/hosts
      subPath: hosts
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"
  volumes:
  - name: gitlab-tls-volume
    secret:
      secretName: gitlab-tls
  - name: custom-hosts
    configMap:
      name: custom-hosts