apiVersion: v1
kind: Pod
metadata:
  name: alpine-light
  namespace: ns-gr
spec:
  containers:
    - name: alpine-light
      image: alpine  # Utilisation de l'image alpine
      # command:
      #   - "sh"
        # - "-c"
        # - |
        #     curl -v --cacert /etc/ssl/certs/gitlab.crt https://gitlab.optiplex3060:9988/
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "512Mi"
          cpu: "500m"
      # volumeMounts:
      #   - name: gitlab-tls
      #     mountPath: /etc/ssl/certs/gitlab.crt
      #     subPath: gitlab.crt  # Nous utilisons directement le certificat du secret
  # volumes:
  #   - name: gitlab-tls
  #     secret:
  #       secretName: gitlab-tls  # Nom du secret que nous voulons utiliser (le certificat)
  restartPolicy: Always  # Utilisation de Always pour le redémarrage automatique
