apiVersion: v1
kind: Pod
metadata:
  name: curl-test
  namespace: ns-gr
spec:
  volumes:
    - name: gitlab-cert
      secret:
        secretName: gitlab-tls
  containers:
    - name: curl-test
      image: alpine
      command: ["sh"]
      stdin: true
      tty: true
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
        requests:
          memory: "64Mi"
          cpu: "250m"
      volumeMounts:
        - name: gitlab-cert
          mountPath: /etc/ssl/certs/gitlab.crt
          subPath: gitlab.crt
  restartPolicy: Never