apiVersion: v1
kind: Pod
metadata:
  name: gitlab-tls-debug-pod-curl-test
  namespace: ns-gr
spec:
  containers:
    - name: gitlab-tls-debug-pod-curl-test
      image: curlimages/curl:latest  # Utilisation de l'image curl prête à l'emploi
      command:
        - "sh"
        - "-c"
        - |
            curl -v --cacert /etc/ssl/certs/gitlab.crt https://gitlab.optiplex3060:9988/
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        - name: gitlab-tls
          mountPath: /etc/ssl/certs/gitlab.crt
          subPath: gitlab.crt  # Nous utilisons directement le certificat du secret
  volumes:
    - name: gitlab-tls
      secret:
        secretName: gitlab-tls  # Nom du secret que nous voulons utiliser (le certificat)
  restartPolicy: Never
